Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: com.aws.lambda.functions.InventoryFindFunction
      CodeUri: C:\Users\JPARODI\GIT\personal\lambda
      Runtime: java17
      Architectures:
        - x86_64